# Sales Performance & Customer Behaviour Analysis for an Online Clothing Retailer

### The company is an online fashion retail store specialising in casual unisex clothing. The brand offering its self-designed clothing line in 23 colours and 9 sizes. It operates solely online from the UK, shipping worldwide, with thoughts of opening a physical store.

In [1]:
import mysql.connector
from dotenv import load_dotenv
import os
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

In [2]:
load_dotenv()

db = mysql.connector.connect(
    host=os.getenv("DB_HOST"),
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    database=os.getenv("DB_NAME")
)
mycursor = db.cursor()
print(db)

<mysql.connector.connection_cext.CMySQLConnection object at 0x00000214DF8B7230>

# Understanding the data

### 
- customers -  customer information
- order_line_items - information on money received, returned and quantity of products
- order_marketing_details - transactions received from different marketign sources
- order_transactions - transaction information
- products - product information

In [3]:
query = "SELECT * FROM customers"
customers_data = pd.read_sql(query,db)

In [4]:
customers_data.head()

,customer_id,email,first_name,last_name,city,country
0,6641683365966,chelseamoss@gmail.com,Chelsea,Moss,Cambridge,United Kingdom
1,6642392563790,jordanburum@gmail.com,Jordan,Burum,York,United Kingdom
2,6640932814926,haileywoollen@gmail.com,Hailey,Woollen,Sheffield,United Kingdom
3,6643025117262,victorgula@aol.com,Victor,Gula,Glasgow,United Kingdom
4,6575175925838,tylertoth@yahoo.com,Tyler,Toth,Southampton,United Kingdom

In [5]:
customers_data.shape

(5123, 6)

In [6]:
customers_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5123 entries, 0 to 5122
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  5123 non-null   int64
 1   email        5123 non-null   object
 2   first_name   5123 non-null   object
 3   last_name    5123 non-null   object
 4   city         5123 non-null   object
 5   country      5123 non-null   object
dtypes: int64(1), object(5)
memory usage: 240.3+ KB

In [7]:
customers_data.describe()

        customer_id
count  5.123000e+03
mean   6.431955e+12
std    7.194636e+11
min    6.510917e+11
25%    6.629200e+12
50%    6.641443e+12
75%    6.642429e+12
max    6.643346e+12

In [8]:
query = "SELECT * FROM order_line_items"
order_items_data = pd.read_sql(query,db)

In [9]:
order_items_data.head()

,transaction_line_item_id,order_transaction_id,product_id,full_price_retail,discounts,revenue,quantity,return_reason,currency
0,R12795507310670,RET#3304566,32645808783438,-84,-21.0,0.0,-1,shipping issues or timing,GBP
1,R12795507376206,RET#3304566,28619227922510,-84,-21.0,0.0,-1,shipping issues or timing,GBP
2,R12795507343438,RET#3304566,39614897619022,-99,-25.0,0.0,-1,shipping issues or timing,GBP
3,R12795507408974,RET#3304566,39926153052238,-69,-17.0,0.0,-1,shipping issues or timing,GBP
4,S12795558854734,#3304595,39399871742030,69,13.8,55.2,1,,GBP

In [10]:
order_items_data.shape

(11038, 9)

In [11]:
order_items_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11038 entries, 0 to 11037
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   transaction_line_item_id  11038 non-null  object
 1   order_transaction_id      11038 non-null  object
 2   product_id                11038 non-null  int64
 3   full_price_retail         11038 non-null  int64
 4   discounts                 11038 non-null  float64
 5   revenue                   11038 non-null  float64
 6   quantity                  11038 non-null  int64
 7   return_reason             11038 non-null  object
 8   currency                  11038 non-null  object
dtypes: float64(2), int64(3), object(4)
memory usage: 776.2+ KB

In [12]:
order_items_data.describe()

,product_id,full_price_retail,discounts,revenue,quantity
count,1.103800e+04,11038.000000,11038.000000,11038.000000,11038.000000
mean,3.746902e+13,48.757202,5.826935,46.321886,0.669958
std,3.746691e+12,61.209760,13.321820,49.955820,0.812306
min,2.853897e+13,-189.000000,-69.000000,-215.890000,-2.000000
25%,3.284136e+13,64.000000,0.000000,47.200000,1.000000
50%,3.939987e+13,69.000000,0.000000,59.000000,1.000000
75%,4.010636e+13,71.000000,13.800000,69.000000,1.000000
max,4.044095e+13,396.000000,136.740000,356.080000,8.000000

In [13]:
query = "SELECT * FROM order_marketing_details"
order_marketing_details_data = pd.read_sql(query,db)

In [14]:
order_marketing_details_data.head()

,row_id,transaction_id,marketing_source,marketing_medium,marketing_campaign
0,1,RET#3304566,facebook,cpc,fb_prospecting_urbanloom_all_2024
1,2,#3304595,(direct),(none),
2,3,#3304600,facebook,cpc,fb_prospecting_urbanloom_all_2024
3,4,#3304624,facebook,cpc,fb_ts_prospecting_dv24_campaign
4,5,#3304800,google,organic,(organic)

In [15]:
order_marketing_details_data.shape

(5603, 5)

In [16]:
order_marketing_details_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5603 entries, 0 to 5602
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   row_id              5603 non-null   int64
 1   transaction_id      5603 non-null   object
 2   marketing_source    5603 non-null   object
 3   marketing_medium    5603 non-null   object
 4   marketing_campaign  5603 non-null   object
dtypes: int64(1), object(4)
memory usage: 219.0+ KB

In [17]:
order_marketing_details_data.describe()

           row_id
count  5603.00000
mean   2802.00000
std    1617.59111
min       1.00000
25%    1401.50000
50%    2802.00000
75%    4202.50000
max    5603.00000

In [18]:
query = "SELECT * FROM order_transactions"
order_transactions_data = pd.read_sql(query,db)

In [19]:
order_transactions_data.head()

,order_transaction_id,order_transaction_type,order_transaction_date,original_sale_transaction_id,customer_id,return_type,shipped_date,delivered_date,pick_up_date,warehouse_received_date
0,RET#3304555,Return,2024-01-15,#3304555,6640688496718,refund,,,,2024-01-30
1,RET#3304564,Return,2024-01-16,#3304564,6640698523726,refund,,,,2024-01-23
2,RET#3304566,Return,2024-01-08,#3304566,6640701603918,exchange,,,,2024-01-13
3,RET#3304568,Return,2024-01-16,#3304568,6640699932750,refund,,,,2024-01-21
4,RET#3304570,Return,2024-01-15,#3304570,6640703864910,refund,,,,2024-01-27

In [20]:
order_transactions_data.shape

(6351, 10)

In [21]:
order_transactions_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6351 entries, 0 to 6350
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   order_transaction_id          6351 non-null   object
 1   order_transaction_type        6351 non-null   object
 2   order_transaction_date        6351 non-null   object
 3   original_sale_transaction_id  6351 non-null   object
 4   customer_id                   6351 non-null   int64
 5   return_type                   6351 non-null   object
 6   shipped_date                  6351 non-null   object
 7   delivered_date                6351 non-null   object
 8   pick_up_date                  6351 non-null   object
 9   warehouse_received_date       6351 non-null   object
dtypes: int64(1), object(9)
memory usage: 496.3+ KB

In [22]:
order_transactions_data.describe()

        customer_id
count  6.351000e+03
mean   6.444153e+12
std    6.929451e+11
min    6.510917e+11
25%    6.633798e+12
50%    6.641474e+12
75%    6.642439e+12
max    6.643346e+12

In [23]:
query = "SELECT * FROM products"
products_data = pd.read_sql(query,db)

In [24]:
products_data.head()

,product_id,product_category,product_type_code,product_colour,product_size,product_name,cost_price
0,39422053908558,Outerwear,BSTK0101,Clay,1X,Bomber Jacket - Clay / 1X,59.03
1,39422053941326,Outerwear,BSTK0101,Clay,2X,Bomber Jacket - Clay / 2X,59.03
2,39422053810254,Outerwear,BSTK0101,Clay,Medium,Bomber Jacket - Clay / Medium,52.79
3,39422054170702,Outerwear,BSTK0101,Jet Black,1X,Bomber Jacket - Jet Black / 1X,59.03
4,39422054236238,Outerwear,BSTK0101,Jet Black,3X,Bomber Jacket - Jet Black / 3X,60.73

In [25]:
products_data.shape

(843, 7)

In [26]:
products_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 843 entries, 0 to 842
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         843 non-null    int64
 1   product_category   843 non-null    object
 2   product_type_code  843 non-null    object
 3   product_colour     843 non-null    object
 4   product_size       843 non-null    object
 5   product_name       843 non-null    object
 6   cost_price         843 non-null    float64
dtypes: float64(1), int64(1), object(5)
memory usage: 46.2+ KB

In [27]:
products_data.describe()

         product_id  cost_price
count  8.430000e+02  843.000000
mean   3.774529e+13   31.621269
std    3.788716e+12   13.590587
min    2.853897e+13    8.080000
25%    3.289368e+13   23.075000
50%    3.966852e+13   30.580000
75%    4.015458e+13   40.550000
max    4.044095e+13   69.020000